apiVersion: apps/v1
kind: Deployment
metadata:
    name: calsoft-deployment
    namespace: calsoft
spec:
    replicas: 3
    selector:
        matchLabels:
            env: test
    template:
        metadata:
            labels:
                env: test
        spec:
            containers:
                - name: calsoft
                  image: shubh9975/simple-app:v3

---
apiVersion: v1
kind: Service
metadata:
    name: calsoft-service
    namespace: calsoft
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
    selector:
        env: test  
